### ISSUE TITLE
Endless "Skipping heartbeat: no active group:" error messages

### ISSUE THREAD

**Issue by vortec** [aio-libs/aiokafka#44] opened 2016-07-21 08:11 UTC
If I let aiokafka connect to Kafka 0.10 after it has just started, it keeps spamming out these error messages and won't stop:

> [2016-07-21 08:00:04,646] ERROR [aiokafka.group_coordinator]: Skipping heartbeat: no active group: 
> [2016-07-21 08:00:04,747] ERROR [aiokafka.group_coordinator]: Skipping heartbeat: no active group: 
> [2016-07-21 08:00:04,849] ERROR [aiokafka.group_coordinator]: Skipping heartbeat: no active group: 
> [2016-07-21 08:00:04,950] ERROR [aiokafka.group_coordinator]: Skipping heartbeat: no active group:

If I stop my app, keep Kafka running and start my app again it will connect just fine.

This forces me to introduce `sleep()` commands to my code and hope that after an arbitrary delay everything works.

**Comment by vortec** [comment] 2016-07-22 08:06
Same code, different error message:

`ERROR [aiokafka.group_coordinator]: Error in join group 'cms' response: InconsistentGroupProtocolError - 23 - Returned in join group when the member provides a protocol type or set of protocols which is not compatible with the current group.`

Again, this message gets spammed out until I kill the process.

**Comment by Drizzt1991** [comment] 2016-07-22 12:31
Is it running the v0.1.2 or master code?

**Comment by vortec** [comment] 2016-07-22 12:36
It's running `aiokafka==0.1.2`.

**Comment by vortec** [comment] 2016-07-28 12:24
Is there anything I can do to help you reproduce the issue?

**Comment by Drizzt1991** [comment] 2016-08-09 03:33
Hello, sorry for the long absence, I tried different setups, can't get it working. If it's not hard, could you provide:
* Number of Kafka brokers and consumers you're testing on
* Snippet of code, that causes the problem.

As for the 2-nd problem (InconsistentGroupProtocolError) - it should only happen if you have a life update (if you don't shutdown all nodes, but restart them one-at-a-time). If you do that make sure, that the assignment strategy (`partition_assignment_strategy` option) contains the currently in use algorithm for assignment. In simpler words - try to just prepend values to `partition_assignment_strategy`, it will result in the 1st strategy in the list when the update is finished.

**Comment by vortec** [comment] 2016-08-09 13:59
Hi @Drizzt1991 , I made some efforts to make this reproducible for you. I think you are familiar with Docker Compose, so you can clone this repository I created for this issue: https://github.com/vortec/kafka_connect_problem .

If you run `docker-compose up` you should end up with the same error message I'm getting. Maybe not on the first try (because Kafka does some things if a topic does not exist yet), but definitely on the second run. You can modify the code in `python/issue.py` and restart the containers, the modified code will be in place.

To answer your questions nevertheless:

- 1 broker and 1 consumer
- https://github.com/vortec/kafka_connect_problem/blob/master/python/issue.py

Hopefully this helps! If not, please tell me what else you need. And thanks in advance!

**Comment by Drizzt1991** [comment] 2016-08-09 15:25
Thanks, will take a look tomorrow!

**Comment by Drizzt1991** [comment] 2016-08-26 15:24
Hello, sorry for no progress on this. It seems like I will not be able to concentrate on actual development until october. Truth is I am currently travelling around places, like Japan for 3 month, and I can't find enough concentration to work on this. In october I plan to return home, so I will proceed supporting `aiokafka`. 
I am online and will answer any questions and PR's thou.

**Comment by Drizzt1991** [comment] 2016-08-26 15:27
As for the docker compose, I did try it, but it failed to launch. I'm pretty sure it's cause I am using it from virtualbox and the data directory is actually on the host's machine, but I could not solve that.

**Comment by Lawouach** [comment] 2016-10-11 12:35
Hi there,

Just wanted to say I'm seeing the same problem. Everything worked fine and then the Kafka cluster went down, when it came back, the aiokafka consumer started in a loop with:

 `ERROR - Skipping heartbeat: no active group: [Error 15] GroupCoordinatorNotAvailableError`

Running:

`$ bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --new-consumer --list`

I could not see my consumer showing up anylonger. When I restarted my process, the consumer group showed up in that command output.

Note that have I three consumers in that group, with different client ids. 

I know it's a server error but I'm wondering if it's not aiokafka that gets into a loop where it shouldn't somehow. Indeed, other Kafka consumers (from other groups) using different clients worked normally after kafka came back to life.

**Comment by Lawouach** [comment] 2016-10-11 14:43
It's actually rather simple to reply.

Run a single kafka node on your local machine, create a topic with 1 replica and 1 partition, run the consumer found at http://aiokafka.readthedocs.io/en/stable/examples/python35_examples.html. Initially you can consume fine. Now stop the kafka broker (Ctrl-C on the process). The consumer goes into the loop about the missing coordinator. That's fair.

Now, restart Kafka, the consumer keeps looping and Kafka tells us this:

`[2016-10-11 16:36:31,215] INFO [GroupCoordinator 0]: Preparing to restabilize group mygroup with old generation 1 (kafka.coordinator.GroupCoordinator)
[2016-10-11 16:36:31,418] INFO [GroupCoordinator 0]: Group mygroup generation 1 is dead and removed (kafka.coordinator.GroupCoordinator)
`

Restarting the consumer process, things come back to normal:

`[2016-10-11 16:39:41,331] INFO [GroupCoordinator 0]: Preparing to restabilize group mygroup with old generation 0 (kafka.coordinator.GroupCoordinator)
[2016-10-11 16:39:41,339] INFO [GroupCoordinator 0]: Stabilized group mygroup generation 1 (kafka.coordinator.GroupCoordinator)
[2016-10-11 16:39:41,349] INFO [GroupCoordinator 0]: Assignment received from leader for group mygroup for generation 1 (kafka.coordinator.GroupCoordinator)
`

Note that, when I restarted Kafka, I got an exception that might be relevant:

`[2016-10-11 16:35:57,409] INFO Creating /controller (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2016-10-11 16:35:57,452] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2016-10-11 16:35:57,453] INFO 0 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
[2016-10-11 16:35:59,200] INFO New leader is 0 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
[2016-10-11 16:35:59,202] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-10-11 16:35:59,204] INFO [ExpirationReaper-0], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-10-11 16:35:59,390] INFO [GroupCoordinator 0]: Starting up. (kafka.coordinator.GroupCoordinator)
[2016-10-11 16:35:59,391] INFO [GroupCoordinator 0]: Startup complete. (kafka.coordinator.GroupCoordinator)
[2016-10-11 16:35:59,404] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 21 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-10-11 16:35:59,419] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2016-10-11 16:35:59,427] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2016-10-11 16:35:59,434] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2016-10-11 16:35:59,487] ERROR [KafkaApi-0] Error when handling request {topics=[test]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2016-10-11 16:35:59,498] ERROR [KafkaApi-0] Error when handling request {topics=[test]} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:670)
	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2016-10-11 16:35:59,525] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2016-10-11 16:35:59,566] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2016-10-11 16:35:59,570] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT -> EndPoint(sylvain-work,9092,PLAINTEXT) (kafka.utils.ZkUtils)
[2016-10-11 16:35:59,594] INFO Kafka version : 0.10.0.0 (org.apache.kafka.common.utils.AppInfoParser)
[2016-10-11 16:35:59,594] INFO Kafka commitId : b8642491e78c5a13 (org.apache.kafka.common.utils.AppInfoParser)
[2016-10-11 16:35:59,603] INFO [Kafka Server 0], started (kafka.server.KafkaServer)
`

**Comment by Lawouach** [comment] 2016-10-11 14:45
I'm running:

```
aiokafka==0.1.2
kafka-python==1.3.1
```

on Python 3.5.2 with kafka 2.11-0.10.0.0

**Comment by Lawouach** [comment] 2016-10-11 15:52
It appears, this is only an issue with auto commit is enabled. When I disable it and run a commit myself, the group corrdinator doesn't go into a loop.

I don't have a patch unfortunately but I hope the investigation helps.

**Comment by vortec** [comment] 2016-10-11 15:55
@Lawouach thanks for your investigation!

But, IIRC, I was using `'enable_auto_commit': False` in my production code.

**Comment by vortec** [comment] 2016-10-11 15:57
Even in the repository I created I am not using auto commit:
https://github.com/vortec/kafka_connect_problem/blob/master/python/issue.py#L67

**Comment by Lawouach** [comment] 2016-10-11 16:01
At least, that seemed to help me. That's worrying if that doesn't fix it in all cases.

I do hope @Drizzt1991 can find some time to look at that issue as this makes aiokafka a little unreliable in the face of Kafka downtime.

**Comment by Lawouach** [comment] 2016-10-14 20:38
I think I have found the issue (in my scenario anyhow). When kafka goes down and backup again, aiokafka tries to re-join. However, when auto-commit is true, the group_coordinator module tries to commit an offset before trying to join. However, in commit_offsets() we have this:

```python
        if (yield from self.coordinator_unknown()):
            raise Errors.GroupCoordinatorNotAvailableError()
```

Since we are indeed without coordinator, the exception will be raised. In other words, the code sees it needs to rejoin, it tries to commit but to do so it needs to be joined already. Nice deadlock (sort of).

Do we really need to commit offsets before we rejoin?

https://github.com/aio-libs/aiokafka/blob/master/aiokafka/group_coordinator.py#L215

Maybe we shouldn't not commit when we know we don't have a coordinator.

**Comment by Lawouach** [comment] 2016-10-14 21:02
Hopefully this will be reviewed and accepted, then released quickly. My project relies on that fix. cc @Drizzt1991 thanks :)

**Comment by Drizzt1991** [comment] 2016-10-16 11:14
Hi there, thanks for the interest and providing debug information. I did plan to spare some free time on the week to work on ``aiokafka``. Will get into this one right away than, will keep in touch on the progress.

**Comment by Drizzt1991** [comment] 2016-10-16 12:32
@Lawouach Hi, I did try to reproduce your issue, but it reconnected perfectly fine for me after spamming some unreadable errors like: 
```
Unable connect to node with id 0: [Errno 111] Connect call failed ('127.0.1.1', 9092)
```
What concerns me is how did you setup those 2 to work:
```
aiokafka==0.1.2
kafka-python==1.3.1
```
I tried using `kafka-python==1.0.1` and it reconnected. When I tried to install `kafka-python==1.3.1` It conflicted like so:
```
Traceback (most recent call last):
  File "examples/simple_consumer-3.5.py", line 18, in <module>
    loop.run_until_complete(consume())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "examples/simple_consumer-3.5.py", line 11, in consume
    await consumer.start()
  File "/workspace/aiokafka/aiokafka/consumer.py", line 173, in start
    yield from self._client.bootstrap()
  File "/workspace/aiokafka/aiokafka/client.py", line 89, in bootstrap
    metadata_request = MetadataRequest([])
TypeError: 'list' object is not callable
```
Maybe you are using the `master` branch rather than `aiokafka==0.1.2`?

**Comment by Drizzt1991** [comment] 2016-10-16 12:34
Will try to track it down by the tracebacks provided, maybe I can get it to brake in my setup. If not will try to setup a proper cluster.

**Comment by Drizzt1991** [comment] 2016-10-16 13:21
Ok @Lawouach I was able to confirm the problem on ``aiokafka==0.1.2`` and on ``master`` branch. Will do a release today or tomorrow morning.

**Comment by Drizzt1991** [comment] 2016-10-16 15:47
@vortec Hi, I've looked into the docker-compose and got it to work, the problem is reproduced, but it is not a problem of the library, as I can see. I've put on debuging and clearly see, that the coordinator is actually not being elected in the Kafka cluster. 
```
python_1     | [2016-10-16 15:09:43,838] DEBUG [aiokafka]: Sending metadata request MetadataRequest(topics=['test-topic']) to 1002
python_1     | [2016-10-16 15:09:43,840] DEBUG [aiokafka.conn]: <AIOKafkaConnection host=62e8254a3710 port=9092> Response 39: MetadataResponse(brokers=[(node_id=1002, host='62e8254a3710', port=9092)], topics=[(error_code=0, topic='test-topic', partitions=[(error_code=5, partition=0, leader=-1, replicas=[], isr=[])])])
python_1     | [2016-10-16 15:09:43,841] DEBUG [kafka.cluster]: Updated cluster metadata to Cluster(brokers: 1, topics: 1, groups: 0)
python_1     | [2016-10-16 15:09:43,842] DEBUG [aiokafka.group_coordinator]: Issuing group metadata request to broker 1002
python_1     | [2016-10-16 15:09:43,844] DEBUG [aiokafka.conn]: <AIOKafkaConnection host=62e8254a3710 port=9092> Response 40: GroupCoordinatorResponse(error_code=15, coordinator_id=-1, host='', port=-1)
python_1     | [2016-10-16 15:09:43,844] ERROR [aiokafka.group_coordinator]: Group Coordinator Request failed: GroupCoordinatorNotAvailableError - 15 - The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.
```

I've also tried with ``kafka-python`` and got the same result:
```
python_1     | [2016-10-16 15:38:12,940] DEBUG [kafka.coordinator]: Issuing group metadata request to broker 1002
python_1     | [2016-10-16 15:38:12,940] DEBUG [kafka.conn]: <BrokerConnection host=62e8254a3710 port=9092> Request 242: GroupCoordinatorRequest(consumer_group='test')
python_1     | [2016-10-16 15:38:12,977] DEBUG [kafka.conn]: <BrokerConnection host=62e8254a3710 port=9092> Response 242: GroupCoordinatorResponse(error_code=15, coordinator_id=-1, host='', port=-1)
python_1     | [2016-10-16 15:38:12,978] DEBUG [kafka.coordinator]: Group metadata response GroupCoordinatorResponse(error_code=15, coordinator_id=-1, host='', port=-1)
python_1     | [2016-10-16 15:38:12,978] DEBUG [kafka.coordinator]: Group Coordinator Not Available; retry
```
Could not find

**Comment by Drizzt1991** [comment] 2016-10-16 20:46
Will leave it till I don't fix the logging to be more appropriate for those cases. They did change it in both Java and Python-kafka libraries.

**Comment by Drizzt1991** [comment] 2016-10-16 20:46
@Lawouach Could you please check if #57 fixes problem on your side? Or you need a release to do that?

**Comment by Lawouach** [comment] 2016-10-17 15:46
Hi @Drizzt1991,

Thanks for spending time on this. Your change seems to work just fine indeed. I wouldn't mine a release because it's always better to pin to a given version.

But, for now, I can pin to that commit.

**Comment by Drizzt1991** [comment] 2016-10-17 18:09
Thanks for testing it. Lets shit it than

**Comment by Lawouach** [comment] 2016-10-18 08:27
Thanks!

I assume you'll cut a proper release in Pypi and here too?

**Comment by Drizzt1991** [comment] 2016-10-18 08:31
In process atm =)

**Comment by Drizzt1991** [comment] 2016-10-18 08:37
Done https://pypi.python.org/pypi/aiokafka/0.1.3

**Comment by Lawouach** [comment] 2016-10-18 08:38
Excellent! thank you ;)

**Comment by Drizzt1991** [comment] 2017-02-17 21:43
We did a bit more logging in master as of now. It should also have a bit better error too, so I will probably close it.

**Closed by Drizzt1991** 2017-02-17 21:43 UTC
