### ISSUE TITLE
Consumer: limit number of messages to read

### ISSUE THREAD

**Issue by shaloba** [aio-libs/aiokafka#574] opened 2020-01-20 08:55 UTC
I'm using aiokafka consumer to pull messages from certain topic. 
I have 5 workers in the same group id and thousands of messages.  
The issue is that the consumer is constantly reading the messages before he finished the once he took and the event loop tasks increasing to a point the event loop takes a lot of time to process the first tasks that came to the queue. 

there is a way to limit the coroutine size so the worker will release the first task more efficiently ? 
if you have example for that it will be great! 

Thanks in advances

**Comment by tvoinarovskyi** [comment] 2020-01-20 11:09
By design, the consumer will not issue a new fetch for partitions that have pending messages in memory, so it should not load more messages than for 1 return of ``getmany()``. So it kind of puzzles me where you see this behaviour, maybe you run a coroutine per each message received in a style similar to this one:

```python
async for message in consumer:
    asyncio.create_task(process_message(message))
```

In that case, I would recommend using an asyncio.Queue and push into it and have several coroutines taking items from it. But it all depends on what your usecase is. There are a few examples in the documentation https://aiokafka.readthedocs.io/en/stable/examples.html, but probably not something you want. 

Could you share how do you process messages, maybe an example of the code you are running? And what is your use-case, usually I process the whole batch of messages from ``getmany()`` concurrently, commit and get the next one. It's quite hard to commit correctly if each incoming message just spawns a coroutine (sadly Kafka can only commit _up to a point_, not _one message at a time_). Will help with what I can =)

**Comment by shaloba** [comment] 2020-01-20 11:36
Hi @tvoinarovskyi , thanks for your response! 
Yep im using the create_task with the callback for the processing. my code looks something like this 

```
import uuid
import time
import asyncio
import logging
from aiokafka import AIOKafkaConsumer, AIOKafkaProducer
from kafka_client import config


logger = logging.getLogger(__name__)
loop = asyncio.get_event_loop()


class KafkaClient(object):
    def __init__(self, *topics, group_id=None):
        """
        Class constructor
        :param group_id: group ID for shared subscribers
        :param topics: list of topic to subscribe
        """
        self.topics = topics
        connection_config = dict(loop=loop, bootstrap_servers=config.KAFKA_SERVER)
        if group_id is not None:
            connection_config['group_id'] = group_id
        self.producer = AIOKafkaProducer(
            loop=loop, bootstrap_servers=config.KAFKA_SERVER,
            key_serializer=str.encode,
            value_serializer=lambda m: json.dumps(m).encode('utf-8'))
        if self.topics:
            self.consumer = AIOKafkaConsumer(*self.topics, **connection_config)

    async def start_producer(self, app):
        await self.producer.start()

    async def consume(self, callback=None):
        tasks = []
        if callback:
            await callback()

        await self.producer.start()
        await self.consumer.start()
        try:
            async for msg in self.consumer:
                try:
                    message = json.loads(msg.value)
                    tasks.append(loop.create_task(self.handle_message(message, msg.key, msg.topic)))
                except Exception as err:
                    logger.exception('Failed to process message [msg]: %s [err]: %s' % (msg.value, err))

        finally:
            # Will leave consumer group; perform autocommit if enabled.
            await self.consumer.stop()
        await asyncio.gather(*tasks)

    def start_consume(self, callback=None):
        logger.info('Start consume [topics]: %s' % self.topics)
        loop.run_until_complete(self.consume(callback))
```

**Comment by tvoinarovskyi** [comment] 2020-01-20 15:41
Great, so it was similar to what I expected. Here are a few recommendations:

- remove from the list of tasks on task finish (this will make the tasks list not leak)
- monitor the list and wait if it goes over a certain limit

Here is some code that handles the changes:
```
import uuid
import time
import asyncio
import logging
from aiokafka import AIOKafkaConsumer, AIOKafkaProducer
from kafka_client import config


logger = logging.getLogger(__name__)
loop = asyncio.get_event_loop()

MAX_CONCURRENCY = 20


class KafkaClient(object):
    def __init__(self, *topics, group_id=None):
        """
        Class constructor
        :param group_id: group ID for shared subscribers
        :param topics: list of topic to subscribe
        """
        self.topics = topics
        connection_config = dict(loop=loop, bootstrap_servers=config.KAFKA_SERVER)
        if group_id is not None:
            connection_config['group_id'] = group_id
        self.producer = AIOKafkaProducer(
            loop=loop, bootstrap_servers=config.KAFKA_SERVER,
            key_serializer=str.encode,
            value_serializer=lambda m: json.dumps(m).encode('utf-8'))
        if self.topics:
            self.consumer = AIOKafkaConsumer(*self.topics, **connection_config)

    async def start_producer(self, app):
        await self.producer.start()

    async def consume(self, callback=None):
        tasks = set()
        if callback:
            await callback()

        await self.producer.start()
        await self.consumer.start()
        try:
            async for msg in self.consumer:
                try:
                    message = json.loads(msg.value)
                except Exception as err:
                    logger.exception('Failed to parse message [msg]: %s [err]: %s' % (msg.value, err))

                task = loop.create_task(self.handle_message(message, msg.key, msg.topic))
                tasks.add(task)
                task.add_done_callback(lambda task, tasks=tasks: tasks.remove(task))

                # We are fine waiting for at least 1 task to free up the queue, as we
                # put 1 in and wait 1 out.
                if len(tasks) > MAX_CONCURRENCY:
                    await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
        finally:
            # Will leave consumer group; perform autocommit if enabled.
            await self.consumer.stop()

        if tasks:
            await asyncio.gather(*tasks)

    def start_consume(self, callback=None):
        logger.info('Start consume [topics]: %s' % self.topics)
        loop.run_until_complete(self.consume(callback))
```

**Comment by tvoinarovskyi** [comment] 2020-01-20 15:49
Do note, that this code does automatic commits every several seconds, so the returned messages may be committed while not really processed and will never be replayed. Ie. :
* Your `handle_message` should have some code handling retries (one example would be putting message back into the same/another topic)
* In rare cases you can lose the message if it was committed before being processed and process killed.
* In rare cases you can deliver the message 2ce if it was processed, but not committed.

I would recommend not being too enthusiastic about making it perfect from this point, as writing exactly-once delivery is quite hard in your situation and this only applies if you actually kill the application, which should not be too often.

**Comment by tvoinarovskyi** [comment] 2020-05-11 20:37
Hope it helped you solve the issue. Please feel free to open a new one if other clarifications needed.

**Closed by tvoinarovskyi** 2020-05-11 20:37 UTC
