### ISSUE TITLE
Assertion failing in consumer fetcher

### ISSUE THREAD

**Issue by vineet-rh** [aio-libs/aiokafka#258] opened 2017-11-15 04:40 UTC
Hi, I am getting the following assertion error:

```
 File "env/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 489, in position
    yield from self._update_fetch_positions([partition])
  File "env/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 879, in _update_fetch_positions
    yield from self._fetcher.update_fetch_positions(partitions)
  File "env/lib/python3.6/site-packages/aiokafka/consumer/fetcher.py", line 517, in update_fetch_positions
    yield from asyncio.gather(*futures, loop=self._loop)
  File "env/lib/python3.6/site-packages/aiokafka/consumer/fetcher.py", line 561, in _reset_offset
    assert timestamp is not None
AssertionError
```

Is there any known issue that might be causing this?

**Comment by tvoinarovskyi** [comment] 2017-11-16 14:15
Yea, I do see it sometimes on tests. Probably a race condition. Also https://github.com/aio-libs/aiokafka/issues/199

**Comment by tvoinarovskyi** [comment] 2017-11-16 14:15
Do you use `seek_to_beginning` or `seek_to_end` in your code?

**Comment by vineet-rh** [comment] 2017-11-20 22:09
Yes I do. I also use the `seek` method.

**Comment by tvoinarovskyi** [comment] 2017-11-21 06:17
Is it possible to provide a code snippet of how you use it? I do know what happens in this case, but I can't reproduce it reliably.

**Comment by vineet-rh** [comment] 2017-11-30 22:29
I was doing something like the following:
```
await consumer.seek_to_end()
await consumer.position() # To make sure the seek definitely completes at this point as I need the offset
```
I was able to get around the issue as the above workflow wasn't really necessary but that is essentially what was giving me the error once in a while. Hope it helps.

**Comment by tvoinarovskyi** [comment] 2017-12-01 05:05
Will try to reproduce it. Want to fix this for 4.0 if possible.

**Comment by tvoinarovskyi** [comment] 2018-01-22 13:02
Should be fixed by https://github.com/aio-libs/aiokafka/pull/286.

**Comment by tvoinarovskyi** [comment] 2018-01-22 13:03
Really sorry for the wait, but it was a hard refactor...

**Closed** 2018-01-26 19:35 UTC
Labels: critical
